"""
This type stub file was generated by pyright.
"""

from typing import Union

from core.models.llm.model import LLMModel
from core.models.lmv3.model import LMv3Model
from core.models.ocr.model import OcrModel

MODELS = Union[LMv3Model, LLMModel, OcrModel]
