"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, Dict, Optional

from structlog.typing import FilteringBoundLogger


class BaseCache(ABC):
    """Base class for all cache implementations.
    """
    logger: FilteringBoundLogger
    def __init__(self, caches_dir: Optional[Path] = ...) -> None:
        ...
    
    @abstractmethod
    def normalize_kwargs(self, **kwargs) -> Dict[str, Any]:
        ...
    
    def generate_hash(self, **kwargs): # -> str:
        ...
    
    def set(self, key: str, value: Dict[str, Any], schematism: Optional[str] = ..., filename: Optional[str] = ...): # -> None:
        ...
    
    def __len__(self) -> int:
        ...
    


