"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

from core.caches.base_cache import BaseCache


class LLMCache(BaseCache):
    def __init__(self, model_name: str, caches_dir: Optional[Path] = ...) -> None:
        ...
    
    def normalize_kwargs(self, **kwargs): # -> dict[str, Any]:
        ...
    


