"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional

from core.caches.base_cache import BaseCache


class LMv3Cache(BaseCache):
    def __init__(self, checkpoint: str, caches_dir: Optional[Path] = ...) -> None:
        ...
    
    def normalize_kwargs(seslf, **kwargs) -> Dict[str, Any]:
        ...
    


