"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any, Dict, Optional

from core.caches.base_cache import BaseCache


class BaseOcrCache(BaseCache):
    """Base cache model for OCR models.
    """
    def __init__(self, cache_dir: Optional[Path] = ...) -> None:
        ...
    
    def normalize_kwargs(self, **kwargs) -> Dict[str, Any]:
        ...
    


class PyTesseractCache(BaseOcrCache):
    def __init__(self, language: str = ..., caches_dir: Optional[Path] = ...) -> None:
        """Cache wrapper for PyTesseract OCR results.

        Args:
            language: Languages string passed to Tesseract. Used only for logging purposes so that
                separate language setups create their own dedicated cache directory.
            caches_dir: Optional path overriding the default cache directory (taken from the
                ``CACHE_DIR`` environment variable).
        """
        ...
    
    def normalize_kwargs(self, **kwargs) -> Dict[str, Any]:
        ...
    


