"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from typing import Dict, List, Optional, Tuple
from schemas.data.schematism import SchematismPage

class BaseCacheItem(BaseModel):
    metadata: Optional[Dict] = ...


class LLMCacheItem(BaseCacheItem):
    """Cache item model for LLM models.
    """
    response: SchematismPage
    hints: Optional[Dict] = ...


class LMv3CacheItem(BaseCacheItem):
    """Cache item model for LMv3 models.
    """
    raw_predictions: Tuple[List, List, List]
    structured_predictions: SchematismPage
    ...


class BaseOcrCacheItem(BaseCacheItem):
    """Base cache item model for OCR models.
    """
    text: str
    ...


class PyTesseractCacheItem(BaseOcrCacheItem):
    """Cache item model for PyTesseract OCR models.
    """
    bbox: List[Tuple[int, int, int, int]]
    words: List[str]
    ...


