"""
This type stub file was generated by pyright.
"""

from typing import Dict, List, Tuple, Union

from PIL import Image
from omegaconf import DictConfig

from core.models.base import ConfigurableModel

logger = ...
def ocr_page(pil_image: Image.Image, text_only: bool = ...) -> Union[Tuple[List, List], str]:
    """Extract OCR text and bounding boxes from PIL image."""
    ...

class LMv3Model(ConfigurableModel):
    """LayoutLMv3 model wrapper with unified predict interface and caching."""
    def __init__(self, config, enable_cache: bool = ...) -> None:
        ...
    
    @classmethod
    def from_config(cls, config: DictConfig) -> LMv3Model:
        ...
    
    def predict(self, pil_image: Image.Image, raw_predictions: bool = ..., **kwargs) -> Union[Dict, Tuple[List, List, List]]:
        """Predict on PIL image and return JSON results with caching.
        
        Args:
            pil_image: PIL Image object
            raw_predictions: If True, return raw predictions_data (words, bboxes, preds)
        Returns:
            Dictionary with structured prediction results or tuple of raw predictions_data
        """
        ...
    


