"""
This type stub file was generated by pyright.
"""

from typing import List

from pydantic import BaseModel


class ParishEntry(BaseModel):
    """Model for individual parish entry data."""
    deanery: str | None = ...
    parish: str = ...
    dedication: str | None = ...
    building_material: str | None = ...


class PageData(BaseModel):
    """Model for page data containing parish entries."""
    page_number: str | None = ...
    entries: List[ParishEntry] = ...


